name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Validate action.yml
      run: |
        python -c "import yaml; yaml.safe_load(open('action.yml')); print('✅ action.yml is valid')"
        
    - name: Validate Python imports
      run: |
        python -c "import sys; sys.path.insert(0, 'src'); from config import Config; from summarizer import CDKDiffSummarizer; print('✅ All modules import successfully')"
        
    - name: Validate file structure
      run: |
        # Verify required files exist
        test -f action.yml && echo "✅ action.yml present"
        test -f requirements.txt && echo "✅ requirements.txt present"
        test -f src/main.py && echo "✅ src/main.py present"
        test -f src/config.py && echo "✅ src/config.py present"
        test -f src/summarizer.py && echo "✅ src/summarizer.py present"
        test -f README.md && echo "✅ README.md present"
        test -f templates/default.md && echo "✅ templates/default.md present"
        echo "✅ All required files present"
        
    - name: Test basic functionality
      run: |
        # Test configuration structure (without API key)
        python -c "
        import sys
        sys.path.insert(0, 'src')
        from config import Config
        # Test that we can create config class (will fail validation, but that's expected)
        try:
            config = Config()
        except ValueError as e:
            if 'AI API key is required' in str(e):
                print('✅ Config validation working correctly (API key required)')
            else:
                raise e
        "
        
    - name: Validate template syntax
      run: |
        python -c "
        import sys
        sys.path.insert(0, 'src')
        from templates import TemplateManager
        from config import Config
        # Create config with dummy API key for template testing
        import os
        os.environ['OPENAI_API_KEY'] = 'test-key'
        config = Config()
        tm = TemplateManager(config)
        print(f'✅ Templates loaded: {len(tm.templates)} templates available')
        " 