name: CDK Diff Summary

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  summarize-diff:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug repository structure
        run: |
          echo "Root directory contents:"
          ls -la
          echo "Current directory:"
          pwd

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Debug Node.js and npm versions
        run: |
          echo "Node version:"
          node --version
          echo "npm version:"
          npm --version
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la

      - name: Install dependencies
        run: |
          npm install
          npm install -g aws-cdk@latest
          npm install source-map-support
          echo "CDK version:"
          cdk --version

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Safety Check - Verify AWS Account
        run: |
          echo "🔒 SAFETY CHECK: This workflow only performs CDK diff operations"
          echo "🔒 No resources will be created or modified"
          echo "🔒 This operation is free and safe to run"
          echo "🔒 Current AWS Account:"
          aws sts get-caller-identity
          echo "🔒 Current AWS Region:"
          echo "$AWS_REGION"

      - name: Bootstrap CDK (if needed)
        run: |
          echo "Bootstrapping CDK in $AWS_REGION..."
          npx cdk bootstrap aws://085960855804/$AWS_REGION

      - name: Initialize and synthesize CDK app
        run: |
          echo "Current directory before CDK commands:"
          pwd
          echo "Directory contents before CDK commands:"
          ls -la
          
          echo "Running CDK synth (safe, no charges)..."
          npx cdk synth --no-staging
          
          echo "Checking cdk.out directory:"
          ls -la cdk.out || echo "cdk.out directory not found"
          echo "Checking for manifest.json:"
          ls -la cdk.out/manifest.json || echo "manifest.json not found"

      - name: Generate CDK diff
        run: |
          echo "Generating CDK diff (safe, no charges)..."
          npx cdk diff --no-staging --json > cdk-diff.json || echo "{}" > cdk-diff.json
          echo "Checking cdk-diff.json:"
          cat cdk-diff.json || echo "cdk-diff.json not found"

      - name: Summarize and comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python summarize_and_comment.py
