name: CDK Diff Summary

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  summarize-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug repository structure
        run: |
          echo "Root directory contents:"
          ls -la
          echo "Current directory:"
          pwd

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Debug Node.js and npm versions
        run: |
          echo "Node version:"
          node --version
          echo "npm version:"
          npm --version
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la

      - name: Install dependencies
        run: |
          npm install
          npm install -g aws-cdk@latest
          npm install source-map-support
          echo "CDK version:"
          cdk --version

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set dummy AWS credentials
        run: |
          export AWS_ACCESS_KEY_ID=dummy
          export AWS_SECRET_ACCESS_KEY=dummy
          export AWS_DEFAULT_REGION=us-east-1
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la

      - name: Initialize and synthesize CDK app
        run: |
          echo "Current directory before CDK commands:"
          pwd
          echo "Directory contents before CDK commands:"
          ls -la
          
          echo "Running CDK synth..."
          npx cdk synth --no-staging
          
          echo "Checking cdk.out directory:"
          ls -la cdk.out || echo "cdk.out directory not found"
          echo "Checking for manifest.json:"
          ls -la cdk.out/manifest.json || echo "manifest.json not found"

      - name: Generate CDK diff
        run: |
          echo "Generating CDK diff..."
          npx cdk diff --no-staging --json > cdk-diff.json
          echo "Checking cdk-diff.json:"
          ls -la cdk-diff.json || echo "cdk-diff.json not found"

      - name: Summarize and comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python summarize_and_comment.py 