name: CDK Diff Summary

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.ts'
      - '**/*.js'
      - '**/*.py'
      - 'cdk.json'

jobs:
  summarize-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Node.js dependencies
        run: npm install
        
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run CDK diff and summarize
        run: |
          # Set dummy AWS credentials
          export AWS_ACCESS_KEY_ID=dummy
          export AWS_SECRET_ACCESS_KEY=dummy
          export AWS_DEFAULT_REGION=us-east-1
          
          # Run CDK diff with --no-staging to skip actual AWS deployment
          npx cdk diff --no-staging --json > cdk-diff.json
          python summarize_and_comment.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 