name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Validate action
      run: |
        # Test the action with example data
        export OPENAI_API_KEY="test-key"
        export AWS_REGION="us-east-1"
        export CDK_DIFF_FILE="examples/cdk-diff.json"
        export OUTPUT_FORMAT="comment"
        export MODEL="gpt-4"
        export MAX_TOKENS="500"
        export CREATE_ISSUE_IF_NO_PR="false"
        export GITHUB_TOKEN="test-token"
        export GITHUB_EVENT_PATH="/dev/null"
        
        # Run a dry test (should fail gracefully due to invalid API key)
        python src/summarize_cdk_diff.py || echo "Expected failure due to invalid API key"
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false 