name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Validate action structure
      run: |
        # Verify all required files exist
        test -f action.yml && echo "✅ action.yml present"
        test -f src/main.py && echo "✅ src/main.py present"
        test -f requirements.txt && echo "✅ requirements.txt present"
        test -f README.md && echo "✅ README.md present"
        echo "✅ All required files present"
        
    - name: Validate action.yml syntax
      run: |
        python -c "import yaml; yaml.safe_load(open('action.yml')); print('✅ action.yml syntax is valid')"
        
    - name: Test module imports
      run: |
        python -c "
        import sys
        sys.path.insert(0, 'src')
        from config import Config
        from summarizer import CDKDiffSummarizer
        print('✅ All modules import successfully')
        "
        
    - name: Test configuration validation
      run: |
        python -c "
        import sys
        sys.path.insert(0, 'src')
        from config import Config
        # Test that config validation works (will fail without API key, which is expected)
        try:
            config = Config()
        except ValueError as e:
            if 'AI API key is required' in str(e):
                print('✅ Config validation working correctly (API key required)')
            else:
                raise e
        "
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false 