name: Test CDK Diff Summarizer Action

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Test CDK Diff
        run: |
          # Create a realistic test CDK diff JSON
          cat > test-cdk-diff.json << 'EOF'
          {
            "stacks": {
              "TestStack": {
                "create": true,
                "resources": {
                  "MyS3Bucket": {
                    "create": true,
                    "type": "AWS::S3::Bucket"
                  },
                  "MyLambdaFunction": {
                    "create": true,
                    "type": "AWS::Lambda::Function"
                  },
                  "MyLambdaRole": {
                    "create": true,
                    "type": "AWS::IAM::Role"
                  },
                  "MyLambdaPolicy": {
                    "create": true,
                    "type": "AWS::IAM::Policy"
                  },
                  "MyDynamoDBTable": {
                    "create": true,
                    "type": "AWS::DynamoDB::Table"
                  }
                }
              },
              "ExistingStack": {
                "update": true,
                "resources": {
                  "ExistingEC2Instance": {
                    "update": true,
                    "type": "AWS::EC2::Instance"
                  },
                  "OldResource": {
                    "destroy": true,
                    "type": "AWS::S3::Bucket"
                  }
                }
              }
            }
          }
          EOF
          
          echo "Created test CDK diff with:"
          echo "- 1 new stack (TestStack) with 5 new resources"
          echo "- 1 updated stack (ExistingStack) with 1 update and 1 destroy"
          cat test-cdk-diff.json

      - name: Test Action - Issue Only
        uses: ./
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          aws-region: 'us-east-1'
          cdk-diff-file: 'test-cdk-diff.json'
          output-format: 'issue'
          model: 'gpt-4'
          max-tokens: '300'
        id: test-issue

      - name: Test Action - Comment Only
        if: github.event_name == 'pull_request'
        uses: ./
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          aws-region: 'us-east-1'
          cdk-diff-file: 'test-cdk-diff.json'
          output-format: 'comment'
          model: 'gpt-4'
          max-tokens: '300'
        id: test-comment

      - name: Test Action - Both Outputs
        uses: ./
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          aws-region: 'us-east-1'
          cdk-diff-file: 'test-cdk-diff.json'
          output-format: 'both'
          model: 'gpt-4'
          max-tokens: '300'
        id: test-both

      - name: Display Test Results
        run: |
          echo "=== Test Results ==="
          echo "Issue Test Success: ${{ steps.test-issue.outputs.success }}"
          echo "Issue Number: ${{ steps.test-issue.outputs.issue-number }}"
          echo "Summary Length: ${#summary} characters"
          
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Comment Test Success: ${{ steps.test-comment.outputs.success }}"
            comment_summary="${{ steps.test-comment.outputs.summary }}"
            echo "Comment Summary Length: ${#comment_summary} characters"
          fi
          
          echo "Both Test Success: ${{ steps.test-both.outputs.success }}"
          echo "Both Issue Number: ${{ steps.test-both.outputs.issue-number }}"
          both_summary="${{ steps.test-both.outputs.summary }}"
          echo "Both Summary Length: ${#both_summary} characters"
          
          echo "=== Summary Preview ==="
          echo "${{ steps.test-both.outputs.summary }}" | head -20

      - name: Test with Empty Diff
        uses: ./
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          aws-region: 'us-east-1'
          cdk-diff-file: 'empty-diff.json'
          output-format: 'issue'
          model: 'gpt-4'
          max-tokens: '300'
        id: test-empty

      - name: Test with Invalid JSON
        run: |
          echo "invalid json content" > invalid-diff.json
        continue-on-error: true

      - name: Test Action with Invalid JSON
        uses: ./
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          aws-region: 'us-east-1'
          cdk-diff-file: 'invalid-diff.json'
          output-format: 'issue'
          model: 'gpt-4'
          max-tokens: '300'
        id: test-invalid
        continue-on-error: true

      - name: Display Error Test Results
        run: |
          echo "=== Error Test Results ==="
          echo "Empty Diff Test Success: ${{ steps.test-empty.outputs.success }}"
          echo "Invalid JSON Test Success: ${{ steps.test-invalid.outputs.success }}" 