name: Test CDK Diff Summarizer Action

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['.github/workflows/test-action.yml']

jobs:
  test-action:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create mock CDK diff
        run: |
          cat > mock-cdk-diff.json << 'EOF'
          {
            "stacks": {
              "TestStack": {
                "create": true,
                "resources": {
                  "MyS3Bucket": {
                    "create": true,
                    "type": "AWS::S3::Bucket"
                  },
                  "MyLambdaFunction": {
                    "create": true,
                    "type": "AWS::Lambda::Function"
                  }
                }
              },
              "ExistingStack": {
                "update": true,
                "resources": {
                  "ExistingEC2Instance": {
                    "update": true,
                    "type": "AWS::EC2::Instance"
                  }
                }
              }
            }
          }
          EOF
      - name: Test CDK Diff Summarizer Action
        uses: ./
        with:
          cdk-diff-file: 'mock-cdk-diff.json'
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          create-issue-if-no-pr: 'true' 